export const Auth = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
};

export const Schedule = {
  GET_SCHEDULE: "GET_SCHEDULE",
  GET_SCHEDULE_SUCCESSFUL: "GET_SCHEDULE_SUCCESSFUL",
  GET_SCHEDULE_ERROR: "GET_SCHEDULE_ERROR",
};
