export const Auth = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
};

export const Schedule = {
  GET_SCHEDULE: "GET_SCHEDULE",
  GET_SCHEDULE_SUCCESSFUL: "GET_SCHEDULE_SUCCESSFUL",
  GET_SCHEDULE_ERROR: "GET_SCHEDULE_ERROR",
};

export const Subject = {
  GET_SUBJECTS: "GET_SUBJECTS",
  GET_SUBJECTS_SUCCESSFUL: "GET_SUBJECTS_SUCCESSFUL",
  GET_SUBJECTS_ERROR: "GET_SUBJECTS_ERROR",
  SET_CURRENT_SUBJECT: "SET_CURRENT_SUBJECT",
};

export const Group = {
  GET_GROUPS: "GET_GROUPS",
  GET_GROUPS_SUCCESSFUL: "GET_GROUPS_SUCCESSFUL",
  GET_GROUPS_ERROR: "GET_GROUPS_ERROR",
  SET_CURRENT_GROUP: "SET_CURRENT_GROUP",
};
