export const Auth = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
};

export const Schedule = {
  GET_SCHEDULE: "GET_SCHEDULE",
  GET_SCHEDULE_SUCCESSFUL: "GET_SCHEDULE_SUCCESSFUL",
  GET_SCHEDULE_ERROR: "GET_SCHEDULE_ERROR",
  SELECT_CLASSROOM: "ADD_SCHEDULE_DAY",
  SELECT_START_HOUR: "SELECT_START_HOUR",
  SELECT_START_MINUTES: "SELECT_START_MINUTES",
  SELECT_FINISH_HOUR: "SELECT_FINISH_HOUR",
  SELECT_FINISH_MINUTES: "SELECT_FINISH_MINUTES",
  CLEAN_SCHEDULE: "CLEAN_SCHEDULE",
};

export const Subject = {
  GET_SUBJECTS: "GET_SUBJECTS",
  GET_SUBJECTS_SUCCESSFUL: "GET_SUBJECTS_SUCCESSFUL",
  GET_SUBJECTS_ERROR: "GET_SUBJECTS_ERROR",
  SET_CURRENT_SUBJECT: "SET_CURRENT_SUBJECT",
};

export const Group = {
  GET_GROUPS: "GET_GROUPS",
  GET_GROUPS_SUCCESSFUL: "GET_GROUPS_SUCCESSFUL",
  GET_GROUPS_ERROR: "GET_GROUPS_ERROR",
  SET_CURRENT_GROUP: "SET_CURRENT_GROUP",
};

export const Teacher = {
  GET_TEACHERS: "GET_TEACHERS",
  GET_TEACHERS_SUCCESSFUL: "GET_TEACHERS_SUCCESSFUL",
  GET_TEACHERS_ERROR: "GET_GET_TEACHERS_ERROR",
  SET_CURRENT_TEACHER: "SET_CURRENT_TEACHER",
};

export const Classroom = {
  GET_CLASSROOM: "GET_CLASSROOM",
  GET_CLASSROOM_SUCCESSFUL: "GET_CLASSROOM_SUCCESSFUL",
  GET_CLASSROOM_ERROR: "GET_CLASSROOM_ERROR",
  SET_CURRENT_CLASSROOM: "SET_CURRENT_CLASSROOM",
};

export const Admin = {
  SAVE_NEW_SCHEDULE: "SAVE_NEW_SCHEDULE",
  SAVE_NEW_SCHEDULE_SUCCESSFUL: "SAVE_NEW_SCHEDULE_SUCCESSFUL",
  SAVE_NEW_SCHEDULE_ERROR: "SAVE_NEW_SCHEDULE_ERROR",
};
